export const THEME_STORAGE_KEY = 'musaic-theme-settings-v1'

export const UI_SCALE_STORAGE_KEY = 'musaic-ui-scale-percent-v1'
export const HOME_GREETING_TEXT_MODE_STORAGE_KEY = 'musaic-home-greeting-text-mode-v1'
export const ANALYZER_HEIGHT_STORAGE_KEY = 'musaic-analyzer-height-px'
export const ANALYZER_RACK_VISIBILITY_STORAGE_KEY = 'musaic-show-analyzer-rack'
export const JUMP_TO_PLAYING_DESTINATION_STORAGE_KEY = 'musaic-jump-to-playing-destination-v1'
export const WAVEFORM_TIME_DISPLAY_MODE_STORAGE_KEY = 'musaic-waveform-time-display-mode'
export const TRANSPORT_INFO_LINE_MODE_STORAGE_KEY = 'musaic-transport-info-line-mode-v1'
export const ACTIVITY_INDICATOR_EXPERIMENT_STORAGE_KEY = 'musaic-experimental-activity-indicator-enabled-v1'
export const CONTROLLER_SUPPORT_EXPERIMENT_STORAGE_KEY = 'musaic-experimental-controller-support-enabled-v1'

export const ARTIST_BROWSE_MODE_STORAGE_KEY = 'musaic-library-artist-browse-mode-v1'
export const TRACKLIST_BPM_KEY_VISIBILITY_STORAGE_KEY = 'musaic-library-tracklist-bpm-key-visible-v1'
export const TRACKLIST_GENRE_VISIBILITY_STORAGE_KEY = 'musaic-library-tracklist-genre-visible-v1'
export const TRACKLIST_ADDED_DATE_VISIBILITY_STORAGE_KEY = 'musaic-library-tracklist-added-date-visible-v1'
export const TRACKLIST_PLAY_COUNT_VISIBILITY_STORAGE_KEY = 'musaic-library-tracklist-play-count-visible-v1'
export const ALBUM_SORT_MODE_STORAGE_KEY = 'musaic-library-album-sort-mode-v1'
export const INCLUDE_SINGLES_IN_ALBUMS_STORAGE_KEY = 'musaic-library-include-singles-in-albums-v1'
export const INCLUDE_COLLAB_ARTISTS_STORAGE_KEY = 'musaic-library-include-collab-artists-v1'
export const ARTIST_ROOT_VIEW_MODE_STORAGE_KEY = 'musaic-library-artist-view-mode-v1'
export const TRACK_RATINGS_ENABLED_STORAGE_KEY = 'musaic-library-track-ratings-enabled-v1'

export const MUSAIC_SESSION_STATE_STORAGE_KEY = 'musaic-session-state-v1'

export const ANALYZER_PROFILES_STORAGE_KEY = 'musaic-analyzer-profiles-v1'
export const OSCILLOSCOPE_UNDERFILL_STORAGE_KEY = 'musaic-oscilloscope-underfill-enabled'
export const VECTORSCOPE_MULTIBAND_STORAGE_KEY = 'musaic-vectorscope-multiband'
export const WAVEFORM_MULTIBAND_STORAGE_KEY = 'musaic-waveform-multiband'
export const SPECTRUM_HEATMAP_STORAGE_KEY = 'musaic-spectrum-heatmap'

export const EQ_STORAGE_KEY = 'musaic-eq-custom-presets'
export const EQ_DEVICE_PROFILE_STORAGE_KEY = 'musaic-eq-device-profiles-v1'

export const PLAYER_VOLUME_STORAGE_KEY = 'musaic-player-volume-v1'
export const NORMALIZATION_ENABLED_STORAGE_KEY = 'musaic-audio-normalization-enabled-v1'
export const NORMALIZATION_TARGET_STORAGE_KEY = 'musaic-audio-normalization-target-lufs-v1'
export const REPLAYGAIN_MODE_STORAGE_KEY = 'musaic-audio-replaygain-mode-v1'

export const INPUT_BINDINGS_STORAGE_KEY = 'musaic-input-bindings-v1'
export const GLOBAL_INPUT_BINDINGS_STORAGE_KEY = 'musaic-global-input-bindings-v1'

export const DISCORD_RPC_ENABLED_STORAGE_KEY = 'musaic-discord-rpc-enabled'
export const DISCORD_RPC_COVER_ART_ENABLED_STORAGE_KEY = 'musaic-discord-rpc-cover-art-enabled'
export const DISCORD_RPC_SMALL_ICON_ENABLED_STORAGE_KEY = 'musaic-discord-rpc-small-icon-enabled'
export const DISCORD_RPC_COMPACT_STATUS_MODE_STORAGE_KEY = 'musaic-discord-rpc-compact-status-mode-v1'
export const DISCORD_RPC_EXPANDED_INFO_MODE_STORAGE_KEY = 'musaic-discord-rpc-expanded-info-mode-v1'
export const DISCORD_RPC_LINK_DESTINATION_STORAGE_KEY = 'musaic-discord-rpc-link-destination-v1'
export const DISCORD_RPC_PAUSE_CLEAR_MINUTES_STORAGE_KEY = 'musaic-discord-rpc-pause-clear-minutes-v1'

export const LYRICS_DISPLAY_SETTINGS_STORAGE_KEY = 'musaic-lyrics-display-settings-v1'
export const UPDATES_AUTO_CHECK_STORAGE_KEY = 'musaic-updates-auto-check-enabled'
export const LIBRARY_GRAPH_ENABLED_STORAGE_KEY = 'musaic-experimental-library-graph-enabled-v1'
export const LISTENING_STATS_ENABLED_STORAGE_KEY = 'musaic-experimental-listening-stats-enabled-v1'
export const LIBRARY_INTEGRITY_ENABLED_STORAGE_KEY = 'musaic-experimental-library-integrity-enabled-v1'

export const AUDIO_OUTPUT_DEVICE_STORAGE_KEY = 'musaic-audio-output-device'
export const NATIVE_AUDIO_OUTPUT_DEVICE_STORAGE_KEY = 'musaic-native-audio-output-device'
export const PLAYBACK_OUTPUT_MODE_STORAGE_KEY = 'musaic-playback-output-mode-v1'
export const CALIBRATION_INPUT_STORAGE_KEY = 'musaic-audio-calibration-input-device'
export const MULTICHANNEL_STORAGE_KEY = 'musaic-audio-multichannel-enabled'
export const INCLUDE_LFE_DOWNMIX_STORAGE_KEY = 'musaic-audio-include-lfe-downmix-v1'
export const STEREO_UPMIX_MODE_STORAGE_KEY = 'musaic-audio-stereo-upmix-mode-v1'
export const SPATIAL_MODE_STORAGE_KEY = 'musaic-audio-spatial-mode-v1'
export const SPATIAL_LAYOUT_STORAGE_KEY = 'musaic-audio-spatial-layout-v1'
export const CHANNEL_ROUTING_STORAGE_KEY = 'musaic-audio-channel-routing-map'
export const DELAY_PROFILE_STORAGE_KEY_V1 = 'musaic-audio-delay-profiles-v1'
export const DELAY_PROFILE_STORAGE_KEY_V2 = 'musaic-audio-delay-profiles-v2'
export const DEV_DISABLE_GAPLESS_PREBUFFER_STORAGE_KEY = 'musaic-dev-disable-gapless-prebuffer-v1'
export const DEV_DISABLE_STANDARD_ANALYSIS_GRAPH_STORAGE_KEY = 'musaic-dev-disable-standard-analysis-graph-v1'

export const DISCORD_COVER_ART_CACHE_STORAGE_KEY_V1 = 'musaic-discord-cover-art-cache-v1'
export const DISCORD_COVER_ART_CACHE_STORAGE_KEY_V2 = 'musaic-discord-cover-art-cache-v2'
export const DISCORD_COVER_ART_CACHE_STORAGE_KEY_V3 = 'musaic-discord-cover-art-cache-v3'
export const DISCORD_COVER_ART_CACHE_STORAGE_KEY_V4 = 'musaic-discord-cover-art-cache-v4'
export const DISCORD_LEGACY_CLIENT_ID_STORAGE_KEY = 'musaic-discord-rpc-client-id'

export const DEVELOPER_SETTINGS_VISIBILITY_STORAGE_KEY = 'musaic-settings-developer-section-visible-v1'
export const BIT_PERFECT_WARNING_DISMISSED_STORAGE_KEY = 'musaic-bitperfect-warning-dismissed-v1'
